# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-22 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='Titulo del articulo')),
                ('body', models.TextField(verbose_name='Cuerpo del Titulo')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('fe', models.DateField(auto_now_add=True, verbose_name='Emision del Articulo')),
            ],
            options={
                'verbose_name_plural': 'Articulos',
                'ordering': ['title'],
            },
        ),
    ]
