# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-22 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.CharField(max_length=350, verbose_name='Cuerpo del Titulo'),
        ),
    ]
