# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 20:16
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_article', '0003_auto_20180123_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='img',
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name=b'Cuerpo del Articulo'),
        ),
    ]
