# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post_article', '0004_auto_20180124_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=35),
        ),
    ]
