# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_article', '0006_auto_20180131_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=35, verbose_name=b'titulo'),
        ),
    ]
