# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_article', '0007_auto_20180131_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='frase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ti', models.CharField(max_length=35, verbose_name=b'titulo de la frase')),
                ('body', models.TextField(max_length=25, verbose_name=b'Frase del dia')),
            ],
            options={
                'ordering': ['ti'],
                'verbose_name_plural': 'Frase del Dia',
            },
        ),
    ]
