# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_article', '0008_frase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frase',
            name='body',
            field=models.TextField(max_length=30, verbose_name=b'Frase del dia'),
        ),
    ]
