# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-12 11:56
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_article', '0010_auto_20180202_2255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='frase',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Articulos'},
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Cuerpo del Articulo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=35, verbose_name='titulo'),
        ),
    ]
