# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to=b'image:_profile')),
                ('name', models.CharField(max_length=20, verbose_name=b'Nombre')),
                ('bio', models.TextField(verbose_name=b'Bio del profile')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Miembros',
            },
        ),
    ]
