# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20180211_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, upload_to='img_profile'),
        ),
    ]
