# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-14 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_workzone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='workzone',
        ),
    ]
