# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_delete_workzone'),
    ]

    operations = [
        migrations.CreateModel(
            name='foar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name=b'Nombre')),
                ('biog', models.TextField(verbose_name=b'bio de la persona')),
                ('imgs', models.ImageField(blank=True, upload_to=b'Familia_OAR')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name_plural': 'Familia',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, upload_to=b'miembros_comunidad'),
        ),
    ]
