# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20180404_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foar',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Orden Agustinos Recoleto'},
        ),
    ]
