# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20180404_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['name'], 'verbose_name_plural': 'Miembros de la comunidad'},
        ),
    ]
