# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-26 13:06
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=32, verbose_name='Titulo de la Actividad')),
                ('cuerpo', ckeditor.fields.RichTextField(verbose_name='Cuerpo del Articulo')),
                ('fp', models.DateField(auto_now_add=True, verbose_name='Fecha de Publicacion')),
            ],
            options={
                'verbose_name_plural': 'Actividades',
                'ordering': ['titulo'],
            },
        ),
    ]
