# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Actividades'},
        ),
    ]
