# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=20, verbose_name=b'Nombre del grupo')),
                ('bg', models.TextField(verbose_name=b'Bio del grupo')),
                ('ig', models.ImageField(blank=True, upload_to=b'Grupos_comunidad')),
            ],
            options={
                'ordering': ['nm'],
                'verbose_name_plural': 'Grupos de la comunidad',
            },
        ),
        migrations.CreateModel(
            name='santos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nms', models.CharField(max_length=20, verbose_name=b'Nombre del santo')),
                ('bgs', models.TextField(verbose_name=b'bio del santo')),
                ('imgs', models.ImageField(blank=True, upload_to=b'Santos_Comunidad')),
            ],
            options={
                'ordering': ['nms'],
                'verbose_name_plural': 'Santos de la Comunidad',
            },
        ),
    ]
